version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  app:
    build:
      context: .        
      dockerfile: ./app/Dockerfile-app
    env_file:
     - app.env
  redis_refresher:
    build:
      context: .
      dockerfile: ./RedisRefresher/Dockerfile-RedisRefresher
    env_file:
      - app.env
  grpc_client:
    build:
      context: .
      dockerfile: ./grpcClient/Dockerfile-grpcClient
    env_file:
      - app.env
  postgre_sql_operations:
    build:
      context: .
      dockerfile: ./PostgreSQLOperations/Dockerfile-PostgreSQLOperations
    env_file:
      - app.env
