apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgre-sql-operations
  name: postgre-sql-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgre-sql-operations
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rate-limit-rate-limiter-network: "true"
        io.kompose.service: postgre-sql-operations
    spec:
      containers:
        - env:
            - name: DB_SOURCE
              valueFrom:
                configMapKeyRef:
                  key: DB_SOURCE
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
            - name: GO_CLIENT_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: GO_CLIENT_HTTP_PORT
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
            - name: GRPC_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: GRPC_SERVER_ADDRESS
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
            - name: POSTGRES_DB_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB_HTTP_PORT
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
            - name: REDIS_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: REDIS_ADDRESS
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
            - name: REDIS_REFRESHER_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_REFRESHER_HTTP_PORT
                  name: Users-furkanakcadogan-Desktop-rate_limiter-rate-limit--env
          image: postgre-sql-operations
          name: postgre-sql-operations
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
