apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30009  # Yeni port numarası
  selector:
    app: postgres-db
