FROM golang:latest

WORKDIR /app


COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
COPY RateLimiter/rateLimiter.go RateLimiter/rateLimiter.go
RUN go build -o /rateLimiter RateLimiter/rateLimiter.go

CMD ["/rateLimiter"]


