global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
  - job_name: 'myapp'
    static_configs:
      - targets: ['host.docker.internal:8080']
    tls_config:
      insecure_skip_verify: true
