// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: insert_queries.sql

package db

import (
	"context"
)

const insertRateLimit = `-- name: InsertRateLimit :exec
INSERT INTO public.rate_limits (clientid, predefined_limit, remaining_limit) VALUES ($1, $2, $3)
`

type InsertRateLimitParams struct {
	Clientid        string `json:"clientid"`
	PredefinedLimit int32  `json:"predefined_limit"`
	RemainingLimit  int32  `json:"remaining_limit"`
}

// db/query/insert_queries.sql
func (q *Queries) InsertRateLimit(ctx context.Context, arg InsertRateLimitParams) error {
	_, err := q.exec(ctx, q.insertRateLimitStmt, insertRateLimit, arg.Clientid, arg.PredefinedLimit, arg.RemainingLimit)
	return err
}
