// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type RateLimit struct {
	ID              int32  `json:"id"`
	Clientid        string `json:"clientid"`
	PredefinedLimit int32  `json:"predefined_limit"`
	RemainingLimit  int32  `json:"remaining_limit"`
}
