// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: select_queries.sql

package db

import (
	"context"
)

const getRateLimitByClientID = `-- name: GetRateLimitByClientID :one
SELECT id, clientid, predefined_limit, remaining_limit FROM rate_limits WHERE clientid = $1
`

// db/query/select_queries.sql
func (q *Queries) GetRateLimitByClientID(ctx context.Context, clientid string) (RateLimit, error) {
	row := q.queryRow(ctx, q.getRateLimitByClientIDStmt, getRateLimitByClientID, clientid)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.Clientid,
		&i.PredefinedLimit,
		&i.RemainingLimit,
	)
	return i, err
}
