// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: update_queries.sql

package db

import (
	"context"
)

const updateRemainingLimit = `-- name: UpdateRemainingLimit :exec
UPDATE rate_limits SET remaining_limit = $2 WHERE clientid = $1
`

type UpdateRemainingLimitParams struct {
	Clientid       string `json:"clientid"`
	RemainingLimit int32  `json:"remaining_limit"`
}

// db/query/update_queries.sql
func (q *Queries) UpdateRemainingLimit(ctx context.Context, arg UpdateRemainingLimitParams) error {
	_, err := q.exec(ctx, q.updateRemainingLimitStmt, updateRemainingLimit, arg.Clientid, arg.RemainingLimit)
	return err
}
