# Use the official Golang image as a parent image
FROM golang:latest

# Set the working directory in the container
WORKDIR /app

# Copy the Go Modules manifests
COPY go.mod go.sum ./

# Download Go modules
RUN go mod download

# Copy the entire project directory (including internal packages)
COPY . .

# Build the app executable
RUN go build -o /app/app /app/app.go

# Set execute permissions for the app
RUN chmod +x /app/app

# Command to run the executable
CMD ["/app/app"]
