apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: grpc-client
  name: grpc-client-service
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: grpc-client
