apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rate-limiter
  name: rate-limiter-service
spec:
  type: LoadBalancer
  ports:
    - name: "50051" # Dışarıdan erişilecek port
      port: 50051
      targetPort: 50051 # Deployment içindeki hedef port
  selector:
    io.kompose.service: rate-limiter
