apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis-refresher
  name: redis-refresher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-refresher
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/rate-limit-rate-limiter-network: "true"
        io.kompose.service: redis-refresher
    spec:
      containers:
        - name: redis-refresher
          image: 029436851145.dkr.ecr.eu-north-1.amazonaws.com/rate-limit:redis_refresher
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
