// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createRateLimitStmt, err = db.PrepareContext(ctx, createRateLimit); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRateLimit: %w", err)
	}
	if q.deleteAllRateLimitsStmt, err = db.PrepareContext(ctx, deleteAllRateLimits); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllRateLimits: %w", err)
	}
	if q.deleteRateLimitStmt, err = db.PrepareContext(ctx, deleteRateLimit); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRateLimit: %w", err)
	}
	if q.getRateLimitStmt, err = db.PrepareContext(ctx, getRateLimit); err != nil {
		return nil, fmt.Errorf("error preparing query GetRateLimit: %w", err)
	}
	if q.listRateLimitsStmt, err = db.PrepareContext(ctx, listRateLimits); err != nil {
		return nil, fmt.Errorf("error preparing query ListRateLimits: %w", err)
	}
	if q.updateRateLimitStmt, err = db.PrepareContext(ctx, updateRateLimit); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRateLimit: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createRateLimitStmt != nil {
		if cerr := q.createRateLimitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRateLimitStmt: %w", cerr)
		}
	}
	if q.deleteAllRateLimitsStmt != nil {
		if cerr := q.deleteAllRateLimitsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllRateLimitsStmt: %w", cerr)
		}
	}
	if q.deleteRateLimitStmt != nil {
		if cerr := q.deleteRateLimitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRateLimitStmt: %w", cerr)
		}
	}
	if q.getRateLimitStmt != nil {
		if cerr := q.getRateLimitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRateLimitStmt: %w", cerr)
		}
	}
	if q.listRateLimitsStmt != nil {
		if cerr := q.listRateLimitsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRateLimitsStmt: %w", cerr)
		}
	}
	if q.updateRateLimitStmt != nil {
		if cerr := q.updateRateLimitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRateLimitStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	createRateLimitStmt     *sql.Stmt
	deleteAllRateLimitsStmt *sql.Stmt
	deleteRateLimitStmt     *sql.Stmt
	getRateLimitStmt        *sql.Stmt
	listRateLimitsStmt      *sql.Stmt
	updateRateLimitStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		createRateLimitStmt:     q.createRateLimitStmt,
		deleteAllRateLimitsStmt: q.deleteAllRateLimitsStmt,
		deleteRateLimitStmt:     q.deleteRateLimitStmt,
		getRateLimitStmt:        q.getRateLimitStmt,
		listRateLimitsStmt:      q.listRateLimitsStmt,
		updateRateLimitStmt:     q.updateRateLimitStmt,
	}
}
