// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type RateLimitingDb struct {
	ID             int32  `json:"id"`
	Clientid       string `json:"clientid"`
	RateLimit      int32  `json:"rate_limit"`
	RefillInterval int32  `json:"refill_interval"`
}
