FROM golang:latest

WORKDIR /app
# Set default values for environment variables


COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .
COPY grpcClient/grpc_client.go grpcClient/grpc_client.go

RUN go build -o /grpcClient grpcClient/grpc_client.go

CMD ["/grpcClient"]
