FROM golang:latest

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY SqlPrompt/sqlPrompt.go PostgreSQLOperations/PostgreSQLOperation.go

RUN go build -o /sqlPrompt PostgreSQLOperations/PostgreSQLOperation.go

CMD ["/PostgreSQLOperations"]
